### ISSUE TITLE
Deprecation message in readme is invalid

### ISSUE THREAD

**Issue by cjprinse** [etrias-nl/AsyncBundle#13]
AsyncBundle does a lot more than just putting messages on a queue.

I think some parts could be replaced by symfony/messenger. Other parts could not (like executing async schedule command. And other parts should be refactored to be used  with symfony/messenger

**Comment by ro0NL** [comment]
Right! The general idea is to use symfony/scheduler also :) 

updated in 08a8517f7fb31007576b33630e20ea5f7d527e98
